// actionTypes.js
export const TOGGLE_ACTIVITY_POPUP = 'TOGGLE_ACTIVITY_POPUP';
export const TOGGLE_NOTIFICATION_POPUP = 'TOGGLE_NOTIFICATION_POPUP';
export const SETTINGS_POPUP = 'SETTINGS_POPUP';
export const COMMENT_POPUP = 'COMMENT_POPUP';


export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'


// actionTypes.js
export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const FETCH_TASK_DETAILS_REQUEST = 'FETCH_TASK_DETAILS_REQUEST';
export const FETCH_TASK_DETAILS_SUCCESS = 'FETCH_TASK_DETAILS_SUCCESS';
export const FETCH_TASK_DETAILS_FAILURE = 'FETCH_TASK_DETAILS_FAILURE';


export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';


// src/redux/notificationActionTypes.js
export const FETCH_ALL_NOTIFICATIONS_REQUEST = 'FETCH_ALL_NOTIFICATIONS_REQUEST';
export const FETCH_ALL_NOTIFICATIONS_SUCCESS = 'FETCH_ALL_NOTIFICATIONS_SUCCESS';
export const FETCH_ALL_NOTIFICATIONS_FAILURE = 'FETCH_ALL_NOTIFICATIONS_FAILURE';

export const FETCH_UNREAD_NOTIFICATIONS_REQUEST = 'FETCH_UNREAD_NOTIFICATIONS_REQUEST';
export const FETCH_UNREAD_NOTIFICATIONS_SUCCESS = 'FETCH_UNREAD_NOTIFICATIONS_SUCCESS';
export const FETCH_UNREAD_NOTIFICATIONS_FAILURE = 'FETCH_UNREAD_NOTIFICATIONS_FAILURE';

export const MARK_ALL_NOTIFICATIONS_AS_READ_REQUEST = 'MARK_ALL_NOTIFICATIONS_AS_READ_REQUEST';
export const MARK_ALL_NOTIFICATIONS_AS_READ_SUCCESS = 'MARK_ALL_NOTIFICATIONS_AS_READ_SUCCESS';
export const MARK_ALL_NOTIFICATIONS_AS_READ_FAILURE = 'MARK_ALL_NOTIFICATIONS_AS_READ_FAILURE';

export const SET_ACTIVE_ELEMENT = 'SET_ACTIVE_ELEMENT';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';


export const FETCH_MEMBER_DETAILS_REQUEST = 'FETCH_MEMBER_DETAILS_REQUEST';
export const FETCH_MEMBER_DETAILS_SUCCESS = 'FETCH_MEMBER_DETAILS_SUCCESS';
export const FETCH_MEMBER_DETAILS_FAILURE = 'FETCH_MEMBER_DETAILS_FAILURE';


// COMMENTS
export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

export const GET_COMMENT_REQUEST = 'GET_COMMENT_REQUEST';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAILURE = 'GET_COMMENT_FAILURE';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';


// NOTIFICATIONS
export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAILURE = "GET_NOTIFICATION_FAILURE";

export const MARK_READ_NOTIFICATION_REQUEST = "MARK_READ_NOTIFICATION_REQUEST";
export const MARK_READ_NOTIFICATION_SUCCESS = "MARK_READ_NOTIFICATION_SUCCESS";
export const MARK_READ_NOTIFICATION_FAILURE = "MARK_READ_NOTIFICATION_FAILURE";

// activity logs
export const GET_ACTIVITY_LOGS_REQUEST = "GET_ACTIVITY_LOGS_REQUEST";
export const GET_ACTIVITY_LOGS_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_ACTIVITY_LOGS_FAILURE = "GET_ACTIVITY_LOGS_FAILURE";

